name: Create Docker image and push to GHCR

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      -
        name: Build and push the image
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"

          echo "Building image for version #VERSION"

          docker build \
            --build-arg VERSION="$VERSION" \
            --tag "ghcr.io/oral-history-digital/ohtm-dashboard:$VERSION" \
            .
          docker push "ghcr.io/oral-history-digital/ohtm-dashboard:$VERSION"
